# Generated by Django 3.2.4 on 2021-06-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='egresoFundacion',
            fields=[
                ('idEgresoFundacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Egreso fundacion')),
                ('medio_pago_banco', models.CharField(max_length=60, verbose_name='Nombre del banco')),
                ('tarjeta_banco', models.IntegerField(verbose_name='Tarjeta del Banco')),
                ('monto_gasto', models.IntegerField(verbose_name='Monto del Gasto')),
                ('descripccion_gasto', models.CharField(max_length=80, verbose_name='Descripcion del Gasto')),
                ('fecha_gasto', models.DateField(verbose_name='Fecha del Gasto')),
            ],
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('idMedioPago', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Medio de pago')),
                ('nombreTipoTarjeta', models.CharField(max_length=15, verbose_name='Nombre del tipo de Tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuarioDonador',
            fields=[
                ('idTipoUsuarioDonador', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de usuario donador')),
                ('nombreTipoUsuarioDonador', models.CharField(max_length=80, verbose_name='Nombre del tipo de usuario Donador')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioDonador',
            fields=[
                ('rut', models.CharField(max_length=10, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=60, null=True, verbose_name='Apellido')),
                ('email', models.CharField(blank=True, max_length=60, null=True, verbose_name='Email')),
                ('nick', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='Nick')),
                ('password', models.CharField(blank=True, max_length=8, null=True, verbose_name='Contraseña')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('MedioPago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.mediopago')),
                ('tipoUsuarioDonador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tipousuariodonador')),
            ],
        ),
        migrations.CreateModel(
            name='ingresoFundacion',
            fields=[
                ('idIngresoFundacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Ingreso')),
                ('NumeroTarjeta', models.IntegerField(verbose_name='Numero de la tarjeta')),
                ('monto', models.IntegerField(verbose_name='Monto del aporte')),
                ('fecha_pago', models.DateField(verbose_name='Fecha del pago')),
                ('MedioPago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.mediopago')),
                ('UsuarioDonador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuariodonador')),
            ],
        ),
    ]
